<a href="https://colab.research.google.com/github/Namesakenberg/Hyperparameter-Hangout/blob/main/100_on_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

3. Create a null vector of size 10 (★☆☆)


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr=np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

. Reverse a vector (first element becomes last) (★☆☆)


In [ ]:
np.flip(arr)

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr=np.array([1,2,0,0,4,0])
np.where(arr!=0)

(array([0, 1, 4]),)

Create a 3x3 identity matrix (★☆☆)

In [ ]:
arr=np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr=np.random.randn(9).reshape(3,3)
arr

array([[ 0.73635264, -0.34148341,  0.12673788],
       [ 0.31469103, -2.23811736,  0.36396585],
       [ 1.3650898 ,  0.45849448, -1.79097686]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [58]:
arr=np.random.rand(100).reshape(10,10)
arr

array([[0.63075127, 0.66191332, 0.12023005, 0.10377386, 0.46578984,
        0.15029503, 0.2392624 , 0.95083887, 0.69530542, 0.3766468 ],
       [0.19649875, 0.43228308, 0.42971523, 0.26702445, 0.29075079,
        0.81908175, 0.05140995, 0.34970518, 0.6014849 , 0.21005805],
       [0.85463815, 0.254275  , 0.74850776, 0.52390975, 0.41689185,
        0.69047907, 0.26744441, 0.28679778, 0.04071708, 0.40390497],
       [0.60411764, 0.9702901 , 0.29506412, 0.5288837 , 0.71798491,
        0.1834123 , 0.7133738 , 0.40868231, 0.14365994, 0.96437521],
       [0.48430959, 0.26533803, 0.68659113, 0.7794636 , 0.31671194,
        0.34062083, 0.90040584, 0.65658844, 0.11859619, 0.08473406],
       [0.61798385, 0.02760755, 0.88558761, 0.04618518, 0.58411769,
        0.68944217, 0.02383544, 0.74914914, 0.35681238, 0.67197589],
       [0.45586353, 0.20506948, 0.73839521, 0.84489968, 0.21926757,
        0.29965774, 0.76500981, 0.51942413, 0.53062659, 0.03513   ],
       [0.30137002, 0.54203908, 0.5689374

In [59]:
np.max(arr)


0.9795630320830464

In [60]:
np.min(arr)

0.02156987865209048

Create a random vector of size 30 and find the mean value (★☆☆)


In [63]:
arr=np.random.randn(30)
arr


array([-1.30093876, -0.66575766,  1.07607511,  0.10752337, -2.01914367,
       -1.22701957,  0.67790826, -0.27152857,  0.64381918,  0.68700011,
        0.03186429, -0.65881503, -2.77422496, -0.38409446, -1.00594842,
       -0.13187017,  0.37438377, -1.02770796,  0.26587179,  1.09173798,
       -0.4089051 ,  0.26171042,  0.28605174, -1.37339221, -0.91092575,
       -1.46609941,  0.8200041 , -1.4722214 ,  1.2079245 ,  2.7184674 ])

In [64]:
arr.mean()

-0.22827503545711636

Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [73]:
arr=np.ones(16).reshape(4,4)
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

 How to add a border (filled with 0's) around an existing array? (★☆☆)


In [77]:
padded_array = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
padded_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

17. What is the result of the following expression? (★☆☆)

0 * np.nan

np.nan == np.

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

In [83]:
0 * np.nan
# nan = not a number

nan

In [81]:
np.inf > np.nan
 #the answer is false , as np.nan is not considered to be comparable to any other number including np.+-inf

False

In [82]:
np.nan-np.nan

nan

In [84]:
np.nan in set([np.nan])

True

 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [95]:
arr=np.zeros(25).reshape(5,5)
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [102]:
np.fill_diagonal(arr[1:],[1,2,3,4])
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [125]:
arr=np.zeros((8,8))
arr[::2,::2]=1
arr[1::2,1::2]=1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [126]:
arr=np.zeros((8,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [129]:
ans=np.tile(arr,(1,0))
ans

array([], shape=(8, 0), dtype=float64)

 Normalize a 5x5 random matrix

 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★

 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★

What is the output of the following script? (★☆☆)


print(sum(range(5),-1))

from numpy import *

print(sum(range(5),-1))

Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1

Z<Z>Z

28. What are the result of the following expressions? (★☆☆)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)

How to round away from zero a float array ? (★☆☆)

How to find common values between two arrays? (★☆☆)

 Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

 How to get the dates of yesterday, today and tomorrow? (★☆☆)


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

 Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

 Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

 Create a random vector of size 10 and sort it (★★☆)

How to sum a small array faster than np.sum? (★★☆)

Consider two random array A and B, check if they are equal (★★☆)

Make an array immutable (read-only) (★★☆)

Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

7. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

49. How to print all the values of an array? (★★☆)

50. How to find the closest value (to a given scalar) in a vector? (★★☆)

51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

 How to convert a float (32 bits) array into an integer (32 bits) in place?