<a href="https://colab.research.google.com/github/Namesakenberg/Hyperparameter-Hangout/blob/main/Numpy_Jams_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numy vs python lists performance comparison




In [ ]:
import numpy as np
my_arr=np.arange(1000000)
my_list=list(range(1000000))

etime = np.testing.measure('for i in range(1000): np.sqrt(i**2)', times=times)

In [ ]:
times = 10
etime = np.testing.measure('for i in range(1000): np.sqrt(i**2)', times=times)
print("Time for a single execution : ", etime / times, "s")

Time for a single execution :  0.002 s


In [ ]:
# multiply each sequence by 2
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10):my_list2=[x* 2 for x in my_list]

CPU times: user 12.1 ms, sys: 2.82 ms, total: 14.9 ms
Wall time: 17 ms
CPU times: user 630 ms, sys: 169 ms, total: 799 ms
Wall time: 801 ms


Generate a small numpy array


In [ ]:
x=np.random.rand(3,4)
x

array([[0.79070386, 0.15207164, 0.22811308, 0.95110832],
       [0.48475289, 0.17822704, 0.64191942, 0.42742649],
       [0.63601052, 0.38704951, 0.52579012, 0.41875008]])

In [ ]:
x*10

array([[2.26501203, 4.46112463],
       [3.67056779, 0.70127923],
       [0.24158132, 2.01223802]])

In [ ]:
x+x

array([[0.45300241, 0.89222493],
       [0.73411356, 0.14025585],
       [0.04831626, 0.4024476 ]])

In [ ]:
x.shape

(3, 2)

In [ ]:
x.dtype

dtype('float64')

creating ndarrays

In [ ]:
data1=[2,3,95,7,11,11]
array1=np.asarray(data1)

array1

array([ 2,  3, 95,  7, 11, 11])

In [ ]:
data2=[[1,2,3,4,5],[6,7,8,9,10]]
array2=np.array(data2)
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
array2.shape

(2, 5)

In [ ]:

array2.ndim

2

array vs asarray

In [ ]:
A = np.ones((3,2))
A

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.array(A)[2]=2
A
# does not update the last row

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.asarray(A)[2]=2
A
#changes the second row of the previous array

array([[1., 1.],
       [1., 1.],
       [2., 2.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
B=np.empty_like(5)
B
#takes another array and creates a new array of same size and datatype just fills all the entries with 1

array(102037475772714)

typecasting a numpy array (chaning the datatype)


In [ ]:
arr=np.array([1,2,3,4,5])
arr.dtype
float_arr=arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
array1=np.array([1.2,3.4,4.5,-9.88,56.67])
array1.dtype
array1int=array1.astype(np.int32)
array1int

array([ 1,  3,  4, -9, 56], dtype=int32)

Calling astype always creates a new array (a copy of the data), even if the new
 dtype is the same as the old dtype.



Arithmatic with numpy arrays

In [ ]:
arr= np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
1/arr #divide each element by array itself, but as the new array is equal to square of old array terms , each element is divided by square of itelf

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr**0.5  #sq.root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

Basic indexing and slicing

One-dimensional arrays
 are simple; on the surface they act similarly to Python lists:

In [ ]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [ ]:
arr_slice[1]=12345
arr_slice

array([   12, 12345,    12])

In [ ]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])