<a href="https://colab.research.google.com/github/Namesakenberg/Hyperparameter-Hangout/blob/main/Numpy_Jams_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numy vs python lists performance comparison




In [7]:
# multiply each sequence by 2
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10):my_list2=[x* 2 for x in my_list]

CPU times: user 15.1 ms, sys: 0 ns, total: 15.1 ms
Wall time: 15.8 ms
CPU times: user 657 ms, sys: 169 ms, total: 826 ms
Wall time: 830 ms


Generate a small numpy array


In [8]:
x=np.random.rand(3,4)
x

array([[0.85191649, 0.0863786 , 0.98038573, 0.80939208],
       [0.50440286, 0.89759476, 0.56995062, 0.72276397],
       [0.72846127, 0.80550675, 0.27923502, 0.93771464]])

In [9]:
x*10

array([[8.5191649 , 0.863786  , 9.80385725, 8.09392079],
       [5.04402856, 8.97594758, 5.69950621, 7.22763974],
       [7.28461273, 8.05506755, 2.79235024, 9.3771464 ]])

In [10]:
x+x

array([[1.70383298, 0.1727572 , 1.96077145, 1.61878416],
       [1.00880571, 1.79518952, 1.13990124, 1.44552795],
       [1.45692255, 1.61101351, 0.55847005, 1.87542928]])

In [11]:
x.shape

(3, 4)

In [12]:
x.dtype

dtype('float64')

creating ndarrays

In [15]:
data1=[2,3,95,7,11,11]
array1=np.asarray(data1)

array1

array([ 2,  3, 95,  7, 11, 11])

In [18]:
data2=[[1,2,3,4,5],[1,2,3,4,5]]
array2=np.asarray(data2)
array2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [19]:
array2.shape

(2, 5)

In [ ]:

array2.ndim

2

array vs asarray

In [ ]:
A = np.ones((3,2))
A

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.array(A)[2]=2
A
# does not update the last row

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.asarray(A)[2]=2
A
#changes the second row of the previous array

array([[1., 1.],
       [1., 1.],
       [2., 2.]])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
B=np.empty_like(5)
B
#takes another array and creates a new array of same size and datatype just fills all the entries with 1

array(97914496517645)

typecasting a numpy array (chaning the datatype)


In [25]:
arr=np.array([1,2,3,4,5])
arr.dtype
float_arr=arr.astype(np.float64)
float_arr.dtype

dtype('int64')

In [ ]:
array1=np.array([1.2,3.4,4.5,-9.88,56.67])
array1.dtype
array1int=array1.astype(np.int32)
array1int

array([ 1,  3,  4, -9, 56], dtype=int32)

Calling astype always creates a new array (a copy of the data), even if the new
 dtype is the same as the old dtype.



Arithmatic with numpy arrays

In [26]:
arr= np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
1/arr #divide each element by array itself, but as the new array is equal to square of old array terms , each element is divided by square of itelf

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr**0.5  #sq.root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [27]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [28]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

Basic indexing and slicing

One-dimensional arrays
 are simple; on the surface they act similarly to Python lists:

In [113]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
arr[5]

5

In [115]:
arr[5:8]

array([5, 6, 7])

In [116]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [117]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [118]:
arr_slice[1]=12345
arr_slice

array([   12, 12345,    12])

In [119]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [120]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [121]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1]


array([4, 5, 6])

In [46]:
arr2d[0][2]

3

In [47]:
arr2d[0,2]

3

In [94]:
arr2d[:2][2:]

array([], shape=(0, 3), dtype=int64)

In [89]:
ans1[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [76]:
old_values=arr3d[0].copy()
arr3d[0]=69
arr3d

array([[[69, 69, 69],
        [69, 69, 69]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0]=old_values
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[1,0]

array([7, 8, 9])

In [79]:
arr3d[1][0]

array([7, 8, 9])

In [122]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [123]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [125]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
arr2d[1,:2]

array([4, 5])

In [142]:
arr2d[:2,2]

array([3, 6])

In [146]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe',
'Joe'])
data=np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [147]:
data

array([[ 1.33685813,  0.05607505, -0.17357779,  2.01300788],
       [-0.79086231, -2.139283  , -0.19357836, -0.74848317],
       [-1.71277952, -0.53505512,  0.33053835,  1.56731392],
       [ 0.58274602, -0.01323232, -2.51775536, -0.53911142],
       [-1.29318142, -0.30416009, -0.19343281,  2.67875992],
       [ 0.0627668 ,  1.28350504,  1.53372973, -0.57300069],
       [-0.02782815, -0.34415844, -1.04611878, -1.21112543]])

In [174]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [175]:
data[names=='Bob']

array([[ 1.33685813,  0.05607505, -0.17357779,  2.01300788],
       [ 0.58274602, -0.01323232, -2.51775536, -0.53911142]])

In [206]:
data[names=='Bob',3:]

array([[ 2.01300788],
       [-0.53911142]])

In [209]:
cond=names=='Bob'
data[~cond]

array([[-0.79086231, -2.139283  , -0.19357836, -0.74848317],
       [-1.71277952, -0.53505512,  0.33053835,  1.56731392],
       [-1.29318142, -0.30416009, -0.19343281,  2.67875992],
       [ 0.0627668 ,  1.28350504,  1.53372973, -0.57300069],
       [-0.02782815, -0.34415844, -1.04611878, -1.21112543]])

In [213]:
data[(names=='Bob')|(names=='Will')]

array([[ 1.33685813,  0.05607505, -0.17357779,  2.01300788],
       [-1.71277952, -0.53505512,  0.33053835,  1.56731392],
       [ 0.58274602, -0.01323232, -2.51775536, -0.53911142],
       [-1.29318142, -0.30416009, -0.19343281,  2.67875992]])

In [214]:
(names=='Bob')|(names=='Will')

array([ True, False,  True,  True,  True, False, False])

selecting data from an array by boolean indexing always creates a copy of the data , even if returned array is unchanged

The Python keywords and and or do not work with boolean arrays. Use & (and)
 and | (or) instead

In [ ]:
#setting all the values which are lesser than zero to zero

In [223]:
data[data<0]=0
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.0627668 , 1.28350504, 1.53372973, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [224]:
data[names!='Joe']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.0627668 , 1.28350504, 1.53372973, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

FANCY INDEXING

the term fancy indexing is used when the indexing of the array is done using integer array




In [226]:
# suppose we have an 8x4 array
arr=np.empty((8,4))
arr

array([[1.  , 0.  , 0.16, 1.  ],
       [1.  , 0.  , 0.  , 1.  ],
       [1.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  , 1.  ],
       [0.  , 1.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 1.  , 1.  ],
       [1.  , 0.  , 0.75, 1.  ]])

In [227]:
for i in range(8):
  arr[i]=i
arr
#every element is given the value corresponding to its row number

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [230]:
arr[[4,3,0,6]]
# get the subset of rows pass the values in terms of array

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [231]:
arr[[-2,-4]]
# negative terms idicate from the end of the array

array([[6., 6., 6., 6.],
       [4., 4., 4., 4.]])

In [234]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [235]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

# the numbers corresponding to the given inputs were selected, no matter how many dimensions the array have
# the result of fancy indexing is always one dimensional
# unlike  slicing the fancy indexing always copies the data into a new array

array([ 4, 23, 29, 10])